export default
	placeholder: true
	validWhenIsChoice: false
	validWhenRegex: false
	autoWidth: false
	maxWidth: '100%'
	minWidth: 2
	height: 46
	checkmark: true
	keyboard: 'text'
	dropdown: {lockScroll:false}
	choices: null
	minLength: null
	maxLength: null
	inputSibling: 'checkmark'
	mask:
		pattern: false
		placeholder: '_'
		guide: true
		customPatterns: false