QuickField.register 'text', import './text'
QuickField.register 'textarea', import './textarea'
QuickField.register 'select', import './select'
QuickField.register 'choice', import './choice'
QuickField.register 'truefalse', import './truefalse'
# QuickField.register 'file', import './file'
# QuickField.register 'group', import './group'
# QuickField.register 'repeater', import './repeater'